Update app_optimizer

diff --git a/MTK_AI/MTK_AI/AI_MODE/gaming_mode/app_optimizer b/MTK_AI/MTK_AI/AI_MODE/gaming_mode/app_optimizer
--- a/MTK_AI/MTK_AI/AI_MODE/gaming_mode/app_optimizer
+++ b/MTK_AI/MTK_AI/AI_MODE/gaming_mode/app_optimizer
@@ -111,29 +111,62 @@ fi
 #VM Memory & Scheduler optimize
 if [ -f "$CONFIG_DIR/sysctl_tweaks" ]; then
 for param in \
-  "vm.admin_reserve_kbytes=8192" "vm.block_dump=0" "vm.compact_unevictable_allowed=1" \
-  "vm.compaction_proactiveness=20" "vm.dirty_background_bytes=0" "vm.dirty_background_ratio=5" \
-  "vm.dirty_bytes=0" "vm.dirty_expire_centisecs=500" "vm.dirty_ratio=20" \
-  "vm.dirty_writeback_centisecs=500" "vm.dirtytime_expire_seconds=43200" "vm.extfrag_threshold=500" \
-  "vm.extra_free_kbytes=0" "vm.laptop_mode=0" "vm.legacy_va_layout=0" \
-  "vm.lowmem_reserve_ratio=256 32 0" "vm.max_map_count=65530" "vm.min_free_kbytes=65536" \
-  "vm.mmap_min_addr=32768" "vm.mmap_rnd_bits=24" "vm.mmap_rnd_compat_bits=11" \
-  "vm.oom_dump_tasks=1" "vm.oom_kill_allocating_task=0" "vm.overcommit_kbytes=0" \
-  "vm.overcommit_memory=0" "vm.overcommit_ratio=50" "vm.page-cluster=3" \
-  "vm.page_lock_unfairness=5" "vm.panic_on_oom=0" "vm.percpu_pagelist_fraction=0" \
-  "vm.stat_interval=60" "vm.swappiness=10" "vm.unprivileged_userfaultfd=0" \
-  "vm.user_reserve_kbytes=131072" "vm.vfs_cache_pressure=50" "vm.watermark_boost_factor=0" \
+  "vm.admin_reserve_kbytes=8192" \
+  "vm.block_dump=0" \
+  "vm.compact_unevictable_allowed=1" \
+  "vm.compaction_proactiveness=20" \
+  "vm.dirty_background_bytes=0" \
+  "vm.dirty_background_ratio=5" \
+  "vm.dirty_bytes=0" \
+  "vm.dirty_expire_centisecs=500" \
+  "vm.dirty_ratio=20" \
+  "vm.dirty_writeback_centisecs=500" \
+  "vm.dirtytime_expire_seconds=43200" \
+  "vm.extfrag_threshold=500" \
+  "vm.extra_free_kbytes=0" \
+  "vm.laptop_mode=0" \
+  "vm.legacy_va_layout=0" \
+  "vm.lowmem_reserve_ratio=256 32 0" \
+  "vm.max_map_count=65530" \
+  "vm.min_free_kbytes=65536" \
+  "vm.mmap_min_addr=32768" \
+  "vm.mmap_rnd_bits=24" \
+  "vm.mmap_rnd_compat_bits=11" \
+  "vm.oom_dump_tasks=1" \
+  "vm.oom_kill_allocating_task=0" \
+  "vm.overcommit_kbytes=0" \
+  "vm.overcommit_memory=0" \
+  "vm.overcommit_ratio=50" \
+  "vm.page-cluster=3" \
+  "vm.page_lock_unfairness=5" \
+  "vm.panic_on_oom=0" \
+  "vm.percpu_pagelist_fraction=0" \
+  "vm.stat_interval=60" \
+  "vm.swappiness=10" \
+  "vm.unprivileged_userfaultfd=0" \
+  "vm.user_reserve_kbytes=131072" \
+  "vm.vfs_cache_pressure=50" \
+  "vm.watermark_boost_factor=0" \
   "vm.watermark_scale_factor=10" \
-  "kernel.sched_schedstats=0" "kernel.sched_util_clamp_min=0" "kernel.sched_pelt_multiplier=1" \
-  "kernel.sched_latency_ns=2000000" "kernel.sched_min_granularity_ns=500000" \
-  "kernel.sched_wakeup_granularity_ns=500000" "kernel.sched_migration_cost_ns=500000" \
-  "kernel.sched_tunable_scaling=0" "kernel.sched_nr_migrate=32" \
-  "kernel.sched_rr_timeslice_ms=100" "kernel.sched_rt_period_us=1000000" \
-  "kernel.sched_rt_runtime_us=950000" "kernel.sched_util_clamp_max=1024" \
-  "kernel.sched_util_clamp_min_rt_default=0" "kernel.sched_energy_aware=1" \
+  "kernel.sched_schedstats=0" \
+  "kernel.sched_util_clamp_min=0" \
+  "kernel.sched_pelt_multiplier=1" \
+  "kernel.sched_latency_ns=2000000" \
+  "kernel.sched_min_granularity_ns=500000" \
+  "kernel.sched_wakeup_granularity_ns=500000" \
+  "kernel.sched_migration_cost_ns=500000" \
+  "kernel.sched_tunable_scaling=0" \
+  "kernel.sched_nr_migrate=32" \
+  "kernel.sched_rr_timeslice_ms=100" \
+  "kernel.sched_rt_period_us=1000000" \
+  "kernel.sched_rt_runtime_us=950000" \
+  "kernel.sched_util_clamp_max=1024" \
+  "kernel.sched_util_clamp_min_rt_default=0" \
+  "kernel.sched_energy_aware=1" \
   "kernel.sched_child_runs_first=0"
 do
-  sysctl -w "$param" 2>&1 | grep -i "invalid\|error\|cannot" && echo "  ^^^ FAILED: $param"
+    # Fixed syntax: removed trailing spaces, fixed redirection, fixed OR operator
+    sysctl -w "$param" > /dev/null 2>&1 || echo "^^^ FAILED: $param"
 done
 fi
 
