Update disable_thermal

diff --git a/MTK_AI/MTK_AI/AI_MODE/gaming_mode/disable_thermal b/MTK_AI/MTK_AI/AI_MODE/gaming_mode/disable_thermal
--- a/MTK_AI/MTK_AI/AI_MODE/gaming_mode/disable_thermal
+++ b/MTK_AI/MTK_AI/AI_MODE/gaming_mode/disable_thermal
@@ -1,5 +1,16 @@
 #!/system/bin/sh
 #!/data/adb/modules/MTK_AI/busybox sh
+MOD_DIR="/data/adb/modules/MTK_AI"
+# --- BUSYBOX INTEGRATION ---
+BB="$MOD_DIR/busybox"
+[ ! -x "$BB" ] && { echo "FATAL: BusyBox missing"; exit 1; }
+
+# Wrap essential tools
+grep() { "$BB" grep "$@"; }; sed() { "$BB" sed "$@"; }; awk() { "$BB" awk "$@"; }
+cut() { "$BB" cut "$@"; }; head() { "$BB" head "$@"; }; tail() { "$BB" tail "$@"; }
+wc() { "$BB" wc "$@"; }; date() { "$BB" date "$@"; }; ionice() { "$BB" ionice "$@"; }
+renice() { "$BB" renice "$@"; }; mkswap() { "$BB" mkswap "$@"; }; swapon() { "$BB" swapon "$@"; }
+swapoff() { "$BB" swapoff "$@"; }; free() { "$BB" free "$@"; }
 
 # --- Configuration ---
 LOG_FILE="/sdcard/MTK_AI_Engine/MTK_AI_Engine.log"
